### ISSUE TITLE
Generate certificate on course completion

### ISSUE THREAD

**Issue by josalmi** [testmycode/tmc-server#246]
User should be able to download certificate for courses that have enabled the feature. 

Certificate should include:
- Full name of the user (where do we get this?)
- Course name
- Description / Free text
- Listing showing completion percentage of each week OR completion percentage of whole course (could be configurable)
- Course provider logo, preferably configurable per course
- Signature

Could certificate template be included in the course and stored in the server?

We should probably provide verify link in the certificate like coursera does.

**Comment by josalmi** [comment]
Connected to #247

**Comment by josalmi** [comment]
Also we want the certificate to be downloadable  after certain point. So we should make some kind of a unlock condition to that too.

**Comment by jamox** [comment]
And we probably want to store all generated certs and provide way for anyone to validate cert.
