### ISSUE TITLE
Additions to installation instructions

### ISSUE THREAD

**Issue by rlaakkol** [testmycode/tmc-server#252]
I tried a fresh install on an Ubuntu 14.04 server VM, and found the following issues:

Missing dependency: postgresql-server-dev-<" postgres version">

$ cd tmc-server
$ git clone https://github.com/testmycode/tmc-server.git
--> wrong order

$ createuser tmc -s -P
--> Switch to postgres user first

$ sudo useradd -G rvm tmc
--> does not create home directory, and default shell is sh

In sandbox directory:
$ sudo make
--> https://bugs.launchpad.net/ubuntu/+source/multistrap/+bug/1313787 (you seem to have posted the workaround for the issue there, please add it here too)

**Comment by jamox** [comment]
Thanks for the comments, indeed there was some inconsistencies in the installation instructions. 
I did some cleaning up for it: d5f34178ba2ef10273ee266488cb188880973c3d
though there probably still are some inconsistencies.
