### ISSUE TITLE
[API] Download exercises by name without authentication

### ISSUE THREAD

**Issue by nygrenh** [testmycode/tmc-server#401]
An unauthenticated user should be able to download an exercise by knowing its name.

**Comment by jamox** [comment]
This could be like `/api/:version/courses/:name/exercises/:exercise_name`

**Comment by mpartel** [comment]
What's the motivation?

Whatever the solution, it'd be good for the URLs to be the same for both
anonymous and authenticated access. Maybe the index JSON files for the
courses could give download URLs for all exercises but advise clients not
to show them early?

**Comment by nygrenh** [comment]
Our new in-browser MOOC requires this. https://ohjelmointikurssi.github.io/
