### ISSUE TITLE
Java source and target versions for the compiler are still 1.6

### ISSUE THREAD

**Issue by matjojo** [testmycode/tmc-server#486]
Java source and target versions for the compiler are still 1.6. Updating this (and what else needs updating with that) should allow students to use newer Java versions and newer syntax.

After finding out that the local tests didn't work when using newer java syntax I found that the solution was to update the javac.source and the javac.target compiler flags to 7, which would allow the compiler to use newer java syntax (in my example the new(ish) diamond operator for ArrayList and using Strings in a switch).

This fix for local can be seen here: https://github.com/testmycode/tmc-intellij/issues/138 
The same fix should apply to the server software. I don't have ubuntu set up so I can't develop and or test the fix myself sadly. 

[This](https://github.com/testmycode/tmc-server/blob/master/spec/fixtures/exercises/common_files/nbproject/project.properties#L42) is the link to the file and line(s) that need to be updated to allow the newer java syntaxes to work. And [This](https://tmc.mooc.fi/submissions/2108879#files) is a link to a TMC submission that shows the problem.

**Comment by nygrenh** [comment]
The issue isn't really in `tmc-server` -- we have many courses working with Java 7 and Java 8 syntax.

The issue could be solved by updating all the exercise templates in the 2013 OO programming course.

We're planning to do a new Java programming course based on our much more recent Finnish course materials (https://materiaalit.github.io/ohjelmointi-18/) and that's why we haven't been updating the old templates.

**Comment by nygrenh** [comment]
Moving the issue here https://github.com/materiaalit/2013-oo-programming/issues/1

**Comment by nygrenh** [comment]
@matjojo And thanks for reporting this!

**Comment by jen-v** [comment]
@nygrenh could you please provide more information on how to do the following
_"The issue could be solved by updating all the exercise templates in the 2013 OO programming course."_ ?
Which files?

I've changed the `project.properties` values:

```
javac.source=1.8
javac.target=1.8
```

But it seems to have no impact on the server. Getting the same error:

```
[javac] /app/src/Team.java:39: error: lambda expressions are not supported in -source 1.6
    [javac]         players.forEach(player -> System.out.println(player));
    [javac]                                ^
    [javac]   (use -source 8 or higher to enable lambda expressions)
```
