### ISSUE TITLE
TMC Is Super Slow 

### ISSUE THREAD

**Issue by GorillaMunchies** [testmycode/tmc-server#570]
Hello, TMC is behaving super slow today, it has me in a queue that is slowly updating projects and I don't know why. 

![Screen Shot 2023-01-10 at 8 09 43 PM](https://user-images.githubusercontent.com/46169731/211694746-99363dfe-ff43-4705-a059-144f94d0bddb.png)

**Comment by fvkncanvk** [comment]
Having the same issue yesterday and today. After a successful test it gets stuck on uploading to sandbox and then times out.
