### ISSUE TITLE
Course-specific admin privileges

### ISSUE THREAD

**Issue by mpartel** [testmycode/tmc-server#95]
Make it possible to give admin access only to a specific course.

**Comment by jsopakar** [comment]
This is implemented in tmc-teacher-tools project, #278 adds course assistants which link assistants to specific courses. Later, more detailed permissions could be implemented, so that admin/teacher could choose which specific permissions he wants to give to his assistants.

**Comment by jamox** [comment]
This is now done with our teacher/ta priviledges
